version: '2'
services:
    app:
        container_name: app
        build:
            context: ./app
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports:
            - "5000:5000"

    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: ./Dockerfile
        depends_on:
            - app
        ports:
            - "80:80"

    es:
        container_name: es
        build:
            context: ./es
            dockerfile: ./Dockerfile
        ports:
            - "9200:9200"
            - "9300:9300"
